name: Test Push

on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Modify a file
      run: echo "Automated change $(date)" >> automated_changes.txt

    - name: Pull latest changes
      run: |
        git pull origin main

    - name: Check for modified files
      id: git-check
      run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

    - name: Commit and push if modified
      if: steps.git-check.outputs.modified == 'true'
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add -A
        git commit -m "Automated summarization"
        git push
